### ISSUE TITLE
vagrant destroy not releasing disks

### ISSUE THREAD

**Issue by MattFenner** [Azure/vagrant-azure#121] opened 2016-05-06 04:40 UTC
using v1.3 of the plugin when i do vagrant destroy it is not releasing the disks. so when i do destroy and up a bunch of times i end up with a bunch of disks in my azure storage which are leased and cannot be deleted.

the plugin should release them and probably also delete them?

**Comment by Tazzeh** [comment] 2016-05-12 08:04
Seconding this. They're getting a little ridiculous:

![Image](http://i.imgur.com/Qm2So9B.png)

**Comment by devigned** [comment] 2016-05-12 15:56
ouch... Are you building Linux or Windows VMs?

**Comment by visualjazz-mbyrne** [comment] 2016-05-12 22:16
> ouch... Are you building Linux or Windows VMs?

I am using Windows, but I haven't guaranteed it doesn't happen to Linux machines also.

**Comment by Matt-Byrne** [comment] 2016-05-12 22:19
> ouch... Are you building Linux or Windows VMs?

I am using Windows, but I haven't tested to guarantee it doesn't happen to Linux machines also.

**Comment by MattFenner** [comment] 2016-05-16 01:54
i was using windows aswell

**Comment by avishnyakov** [comment] 2016-05-30 23:35
Would (or should) vagrant destroy the data disks as well? 
In case we add more data disks to the VM, would vagrant kill them all?

**Comment by devigned** [comment] 2016-05-31 00:33
This should cease to be an issue after moving to Vagrant-Azure 2.0.

**Comment by terrancesnyder** [comment] 2016-06-05 19:02
I would not destroy data disks with a vagrant destroy command. Currently V2.0 does this because it destroys the entire containiner, but in the pull request made by @devigned he noted the issue of doing as much when you have multiple boxes being run within the same resource group. I'd suggest data disks be a physical action to destroy rather than blindly doing this.

Changing:

```
env[:azure_arm_service].resources.resource_groups.delete(parsed[:group]).value!.body
```

To

```
env[:azure_arm_service].compute.virtual_machines.delete(parsed[:group], parsed[:name]).value!.body
```

Will re-enable that delete should/would not delete resources that expected to stay around.

For example:

In the current release of V2.0 if I brought up a hbase master server, and 5 region servers, a zookeeper box for a total of 7 servers. Doing a "vagrant destroy on ONE of the region servers" would then destroy ALL boxes as well as ALL data associated.

Again, IMHO, and it depends on what the definition of "resource" group is.. Currently resource group in V2.0 is strongly correlated to "a single box". Which is counter to the docs and peoples understanding (security groups are shared assets not specific to a single box, so destroying them... probably not a good idea.)

**Comment by avishnyakov** [comment] 2016-06-05 22:03
> > I would not destroy data disks with a vagrant destroy command.

Well, alright. How would it work in create - destroy - create again scenario? 
Create VMs with Vagrant, destroy (disks are left there), create VMs again with Vagrant and it would not be able to re-create VM again cause disks are there. It would probably get more disks leaving mess from the previous VMs.

Such behaviour is a bit weird. As stated in Vagrant docs, Vagrant should destroy VM and resources as nothing were there - https://www.vagrantup.com/docs/cli/destroy.html

> > This command stops the running machine Vagrant is managing and destroys all resources that were created during the machine creation process. After running this command, your computer should be left at a clean state, as if you never created the guest machine in the first place.

This is expected behaviour for vagrant destroy. So all resources should be deleted. No misinterpretation can be seen.

Next, getting resource group within Vagrant implementation is one more weird step. Vagrant gets VM up and running considering VM to be a single disposable box, a single unit of management. Again, as per Vagrant documentation the box (the VM) is an expected unit of management. That means Vagrant up work with VM, as well as Vagrant destroy works with VM as well (not with Resource Group or ALL VMs in the resource group).

Sum up - vagrant-azure probably should re-consider official Vagrant documentation avoiding introducing its own concepts and other than expected per docs behaviour.

**Comment by terrancesnyder** [comment] 2016-06-07 16:59
@avishnyakov How would create - destroy - create work?

I'll clarify - the OS disks are deleted. The issue is deleting the entire resource group.

For the instance for data disks, it would be fantastic, and expected to keep data disks around and scripts in your puppet to automatically re-attach them.

Think of DR. Your instance is hosed, you have data on attached data disks. You're machine is dead, and you need to bring up a new one.

"vagrant up"
... run your system for 3 months, writing data to attached disks because you did the right thing when running a hbase cluster and seperated your OS disk from your data disks and used premium storage ...
... you decide to destroy a box or the box is destroyed for you in a critical error ...

"vagrant up"
... your new OS brings up, and your puppet scripts re-attach data disks ...

In the current world, the data disks or any other thing like security groups is just blindly deleted in the resource group.

So "vagrant destroy" is nuking everything. I get it, it made it work. the author said as much about having multiple machines.

Now, you could come back and say "we'll that's fine, you should just have a resource group per machine". The issue there is now you've dropped out of microsoft best practice, so now vagrant forces me to violate best practice for resource groups, ACL management, etc. and managing IP and remapping is drastically more complicated.

Further, with a massive compute array of 150+ servers, that becomes a bit of a nightmare.

I've got a fork, I'll submit a pull. People can argue for or against at that time.

**Comment by MattFenner** [comment] 2016-06-08 01:59
I'm not experienced enough with vagrant to say whether it should delete the disks or not.

However my issues are that:
 a) there is no way to tell vagrant to delete the disks, even if this is what i want
 b) the lease is kept on the disks so i cant even delete them through the azure portal if i want to

**Comment by avishnyakov** [comment] 2016-06-08 02:11
@terrancesnyder, DR has little to do with vagrant.

My final word is official Vagrant docs. They stat how it should work: "Vagrant should destroy VM and resources as nothing were there - https://www.vagrantup.com/docs/cli/destroy.html

> > This command stops the running machine Vagrant is managing and destroys all resources that were created during the machine creation process. After running this command, your computer should be left at a clean state, as if you never created the guest machine in the first place.

DR has little to do with Vagrant. Data disks should be backed up, so we would have a copy every X hours or something. Need VMs back - great, here are the backups. 

As for the resource groups, highlighted the same issue - Azure implementation of Vagrant must work with VM as a single box, a single unit. Back to Vagrant docs again. A box is a single unit of management. Absolutely agree that having such management at the resource group level is no-go.

That said, current vagrant-azure implementation has a lot of things to be implemented. Does not seem to be demo/uat/prod ready. We moved to Ansible/Terraform to bootstrap VMs.

**Comment by terrancesnyder** [comment] 2016-06-09 17:53
+1 I think we're blaming the plugin for what is a weird concept in azure as a whole. We'll work around, and if possible I'll put a fork/pull in that compensates and allows an "opt-out".

**Comment by devigned** [comment] 2017-02-02 02:16
If you can move to version v2.0.0.pre2, vagrant-azure will clean up disks, as it wipes out the resource group containing all allocated resources upon destroy.

**Closed by devigned** 2017-02-02 02:16 UTC
